package tf.vo.req;

public class GraphqlRequestVo {

	
	private String operationName = "PostPageQuery";
	
	private VariablesVo  variables;
	
	
	private String query = "query PostPageQuery($postId: ID!, $postMeteringOptions: PostMeteringOptions) {"
			+ "  postResult(id: $postId) {"
			+ "    __typename"
			+ "    ...PostResultError_postResult"
			+ "    ... on Post {"
			+ "      id"
			+ "      collection {"
			+ "        id"
			+ "        googleAnalyticsId"
			+ "        ...PostAuthorInfo_collection"
			+ "        ...MoreFromAuthorAndMaybePub_collection"
			+ "        __typename"
			+ "      }"
			+ "      content(postMeteringOptions: $postMeteringOptions) {"
			+ "        isLockedPreviewOnly"
			+ "        __typename"
			+ "      }"
			+ "      creator {"
			+ "        id"
			+ "        ...MastodonVerificationLink_user"
			+ "        ...SuspendedBannerLoader_user"
			+ "        ...PostAuthorInfo_user"
			+ "        ...MoreFromAuthorAndMaybePub_user"
			+ "        __typename"
			+ "      }"
			+ "      inResponseToEntityType"
			+ "      isLocked"
			+ "      ...Wall_post"
			+ "      ...InteractivePostBody_post"
			+ "      ...WithResponsesSidebar_post"
			+ "      ...PostCanonicalizer_post"
			+ "      ...PostFooterActionsBar_post"
			+ "      ...PostReadTracker_post"
			+ "      ...PostMetadata_post"
			+ "      ...SuspendedBannerLoader_post"
			+ "      ...PostFooterInfo_post"
			+ "      ...PostBodyInserts_post"
			+ "      ...PostNoteMissingToast_post"
			+ "      ...usePostTracking_post"
			+ "      ...InResponseToEntityPreview_post"
			+ "      ...PostPublishedDialog_prerequisite_post"
			+ "      __typename"
			+ "    }"
			+ "  }"
			+ "}"
			+ ""
			+ "fragment PostResultError_postResult on PostResult {"
			+ "  __typename"
			+ "  ... on Post {"
			+ "    id"
			+ "    __typename"
			+ "  }"
			+ "  ... on UnavailableForLegalReasons {"
			+ "    ...UnavailableForLegalReasonsScreen_unavailableForLegalReasons"
			+ "    __typename"
			+ "  }"
			+ "  ... on WithheldInCountry {"
			+ "    ...WithheldInCountryScreen_withheldInCountry"
			+ "    __typename"
			+ "  }"
			+ "}"
			+ ""
			+ "fragment UnavailableForLegalReasonsScreen_unavailableForLegalReasons on UnavailableForLegalReasons {"
			+ "  lumenId"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment WithheldInCountryScreen_withheldInCountry on WithheldInCountry {"
			+ "  lumenId"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment PostAuthorInfo_collection on Collection {"
			+ "  editors {"
			+ "    user {"
			+ "      id"
			+ "      __typename"
			+ "    }"
			+ "    __typename"
			+ "  }"
			+ "  ...CollectionAvatar_collection"
			+ "  ...CollectionLinkWithPopover_collection"
			+ "  __typename"
			+ "  id"
			+ "}"
			+ ""
			+ "fragment CollectionAvatar_collection on Collection {"
			+ "  name"
			+ "  avatar {"
			+ "    id"
			+ "    __typename"
			+ "  }"
			+ "  ...collectionUrl_collection"
			+ "  __typename"
			+ "  id"
			+ "}"
			+ ""
			+ "fragment collectionUrl_collection on Collection {"
			+ "  id"
			+ "  domain"
			+ "  slug"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment CollectionLinkWithPopover_collection on Collection {"
			+ "  ...collectionUrl_collection"
			+ "  ...CollectionTooltip_collection"
			+ "  __typename"
			+ "  id"
			+ "}"
			+ ""
			+ "fragment CollectionTooltip_collection on Collection {"
			+ "  id"
			+ "  name"
			+ "  description"
			+ "  subscriberCount"
			+ "  ...CollectionAvatar_collection"
			+ "  ...CollectionFollowButton_collection"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment CollectionFollowButton_collection on Collection {"
			+ "  __typename"
			+ "  id"
			+ "  name"
			+ "  slug"
			+ "  ...collectionUrl_collection"
			+ "  ...SusiClickable_collection"
			+ "}"
			+ ""
			+ "fragment SusiClickable_collection on Collection {"
			+ "  ...SusiContainer_collection"
			+ "  __typename"
			+ "  id"
			+ "}"
			+ ""
			+ "fragment SusiContainer_collection on Collection {"
			+ "  name"
			+ "  ...SignInOptions_collection"
			+ "  ...SignUpOptions_collection"
			+ "  __typename"
			+ "  id"
			+ "}"
			+ ""
			+ "fragment SignInOptions_collection on Collection {"
			+ "  id"
			+ "  name"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment SignUpOptions_collection on Collection {"
			+ "  id"
			+ "  name"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment MoreFromAuthorAndMaybePub_collection on Collection {"
			+ "  id"
			+ "  name"
			+ "  ...collectionUrl_collection"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment MastodonVerificationLink_user on User {"
			+ "  id"
			+ "  linkedAccounts {"
			+ "    mastodon {"
			+ "      username"
			+ "      __typename"
			+ "      id"
			+ "    }"
			+ "    __typename"
			+ "    id"
			+ "  }"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment SuspendedBannerLoader_user on User {"
			+ "  id"
			+ "  isSuspended"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment PostAuthorInfo_user on User {"
			+ "  id"
			+ "  imageId"
			+ "  mediumMemberAt"
			+ "  ...useIsVerifiedBookAuthor_user"
			+ "  ...PublisherName_publisher"
			+ "  ...PublisherFollowersCount_publisher"
			+ "  ...PublisherDescription_publisher"
			+ "  ...FollowAndSubscribeButtons_user"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment useIsVerifiedBookAuthor_user on User {"
			+ "  verifications {"
			+ "    isBookAuthor"
			+ "    __typename"
			+ "  }"
			+ "  __typename"
			+ "  id"
			+ "}"
			+ ""
			+ "fragment PublisherName_publisher on Publisher {"
			+ "  id"
			+ "  name"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment PublisherFollowersCount_publisher on Publisher {"
			+ "  id"
			+ "  __typename"
			+ "  id"
			+ "  ... on Collection {"
			+ "    slug"
			+ "    subscriberCount"
			+ "    ...collectionUrl_collection"
			+ "    __typename"
			+ "    id"
			+ "  }"
			+ "  ... on User {"
			+ "    socialStats {"
			+ "      followerCount"
			+ "      __typename"
			+ "    }"
			+ "    username"
			+ "    ...userUrl_user"
			+ "    __typename"
			+ "    id"
			+ "  }"
			+ "}"
			+ ""
			+ "fragment userUrl_user on User {"
			+ "  __typename"
			+ "  id"
			+ "  customDomainState {"
			+ "    live {"
			+ "      domain"
			+ "      __typename"
			+ "    }"
			+ "    __typename"
			+ "  }"
			+ "  hasSubdomain"
			+ "  username"
			+ "}"
			+ ""
			+ "fragment PublisherDescription_publisher on Publisher {"
			+ "  __typename"
			+ "  id"
			+ "  ... on Collection {"
			+ "    description"
			+ "    __typename"
			+ "    id"
			+ "  }"
			+ "  ... on User {"
			+ "    bio"
			+ "    __typename"
			+ "    id"
			+ "  }"
			+ "}"
			+ ""
			+ "fragment FollowAndSubscribeButtons_user on User {"
			+ "  ...UserFollowButton_user"
			+ "  ...UserSubscribeButton_user"
			+ "  __typename"
			+ "  id"
			+ "}"
			+ ""
			+ "fragment UserFollowButton_user on User {"
			+ "  ...UserFollowButtonSignedIn_user"
			+ "  ...UserFollowButtonSignedOut_user"
			+ "  __typename"
			+ "  id"
			+ "}"
			+ ""
			+ "fragment UserFollowButtonSignedIn_user on User {"
			+ "  id"
			+ "  name"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment UserFollowButtonSignedOut_user on User {"
			+ "  id"
			+ "  ...SusiClickable_user"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment SusiClickable_user on User {"
			+ "  ...SusiContainer_user"
			+ "  __typename"
			+ "  id"
			+ "}"
			+ ""
			+ "fragment SusiContainer_user on User {"
			+ "  ...SignInOptions_user"
			+ "  ...SignUpOptions_user"
			+ "  __typename"
			+ "  id"
			+ "}"
			+ ""
			+ "fragment SignInOptions_user on User {"
			+ "  id"
			+ "  name"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment SignUpOptions_user on User {"
			+ "  id"
			+ "  name"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment UserSubscribeButton_user on User {"
			+ "  id"
			+ "  isPartnerProgramEnrolled"
			+ "  name"
			+ "  viewerEdge {"
			+ "    id"
			+ "    isFollowing"
			+ "    isUser"
			+ "    __typename"
			+ "  }"
			+ "  viewerIsUser"
			+ "  newsletterV3 {"
			+ "    id"
			+ "    ...useNewsletterV3Subscription_newsletterV3"
			+ "    __typename"
			+ "  }"
			+ "  ...useNewsletterV3Subscription_user"
			+ "  ...MembershipUpsellModal_user"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment useNewsletterV3Subscription_newsletterV3 on NewsletterV3 {"
			+ "  id"
			+ "  type"
			+ "  slug"
			+ "  name"
			+ "  collection {"
			+ "    slug"
			+ "    __typename"
			+ "    id"
			+ "  }"
			+ "  user {"
			+ "    id"
			+ "    name"
			+ "    username"
			+ "    newsletterV3 {"
			+ "      id"
			+ "      __typename"
			+ "    }"
			+ "    __typename"
			+ "  }"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment useNewsletterV3Subscription_user on User {"
			+ "  id"
			+ "  username"
			+ "  newsletterV3 {"
			+ "    ...useNewsletterV3Subscription_newsletterV3"
			+ "    __typename"
			+ "    id"
			+ "  }"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment MembershipUpsellModal_user on User {"
			+ "  id"
			+ "  name"
			+ "  imageId"
			+ "  postSubscribeMembershipUpsellShownAt"
			+ "  newsletterV3 {"
			+ "    id"
			+ "    __typename"
			+ "  }"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment MoreFromAuthorAndMaybePub_user on User {"
			+ "  __typename"
			+ "  id"
			+ "  name"
			+ "  imageId"
			+ "  ...userUrl_user"
			+ "}"
			+ ""
			+ "fragment Wall_post on Post {"
			+ "  content(postMeteringOptions: $postMeteringOptions) {"
			+ "    isLockedPreviewOnly"
			+ "    __typename"
			+ "  }"
			+ "  isLocked"
			+ "  isMarkedPaywallOnly"
			+ "  ...RegWall_post"
			+ "  ...Paywall_post"
			+ "  __typename"
			+ "  id"
			+ "}"
			+ ""
			+ "fragment RegWall_post on Post {"
			+ "  id"
			+ "  lockedSource"
			+ "  ...SusiClickable_post"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment SusiClickable_post on Post {"
			+ "  id"
			+ "  mediumUrl"
			+ "  ...SusiContainer_post"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment SusiContainer_post on Post {"
			+ "  id"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment Paywall_post on Post {"
			+ "  id"
			+ "  creator {"
			+ "    id"
			+ "    name"
			+ "    imageId"
			+ "    __typename"
			+ "  }"
			+ "  primaryTopic {"
			+ "    slug"
			+ "    __typename"
			+ "    id"
			+ "  }"
			+ "  topics {"
			+ "    slug"
			+ "    __typename"
			+ "  }"
			+ "  ...AspirationalPaywall_post"
			+ "  ...ProgrammingPaywall_post"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment AspirationalPaywall_post on Post {"
			+ "  id"
			+ "  creator {"
			+ "    name"
			+ "    __typename"
			+ "    id"
			+ "  }"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment ProgrammingPaywall_post on Post {"
			+ "  id"
			+ "  primaryTopic {"
			+ "    slug"
			+ "    __typename"
			+ "    id"
			+ "  }"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment InteractivePostBody_post on Post {"
			+ "  id"
			+ "  content(postMeteringOptions: $postMeteringOptions) {"
			+ "    isLockedPreviewOnly"
			+ "    bodyModel {"
			+ "      ...PostBody_bodyModel"
			+ "      paragraphs {"
			+ "        ...HighlighSegmentContext_paragraph"
			+ "        ...NormalizeHighlights_paragraph"
			+ "        __typename"
			+ "      }"
			+ "      __typename"
			+ "    }"
			+ "    __typename"
			+ "  }"
			+ "  creator {"
			+ "    id"
			+ "    allowNotes"
			+ "    ...PostBody_creator"
			+ "    __typename"
			+ "  }"
			+ "  ...ActiveSelectionContext_post"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment PostBody_bodyModel on RichText {"
			+ "  sections {"
			+ "    name"
			+ "    startIndex"
			+ "    textLayout"
			+ "    imageLayout"
			+ "    backgroundImage {"
			+ "      id"
			+ "      originalHeight"
			+ "      originalWidth"
			+ "      __typename"
			+ "    }"
			+ "    videoLayout"
			+ "    backgroundVideo {"
			+ "      videoId"
			+ "      originalHeight"
			+ "      originalWidth"
			+ "      previewImageId"
			+ "      __typename"
			+ "    }"
			+ "    __typename"
			+ "  }"
			+ "  paragraphs {"
			+ "    id"
			+ "    ...PostBodySection_paragraph"
			+ "    __typename"
			+ "  }"
			+ "  ...normalizedBodyModel_richText"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment PostBodySection_paragraph on Paragraph {"
			+ "  name"
			+ "  ...PostBodyParagraph_paragraph"
			+ "  __typename"
			+ "  id"
			+ "}"
			+ ""
			+ "fragment PostBodyParagraph_paragraph on Paragraph {"
			+ "  name"
			+ "  type"
			+ "  ...ImageParagraph_paragraph"
			+ "  ...TextParagraph_paragraph"
			+ "  ...IframeParagraph_paragraph"
			+ "  ...MixtapeParagraph_paragraph"
			+ "  ...CodeBlockParagraph_paragraph"
			+ "  __typename"
			+ "  id"
			+ "}"
			+ ""
			+ "fragment ImageParagraph_paragraph on Paragraph {"
			+ "  href"
			+ "  layout"
			+ "  metadata {"
			+ "    id"
			+ "    originalHeight"
			+ "    originalWidth"
			+ "    focusPercentX"
			+ "    focusPercentY"
			+ "    alt"
			+ "    __typename"
			+ "  }"
			+ "  ...Markups_paragraph"
			+ "  ...ParagraphRefsMapContext_paragraph"
			+ "  ...PostAnnotationsMarker_paragraph"
			+ "  __typename"
			+ "  id"
			+ "}"
			+ ""
			+ "fragment Markups_paragraph on Paragraph {"
			+ "  name"
			+ "  text"
			+ "  hasDropCap"
			+ "  dropCapImage {"
			+ "    ...MarkupNode_data_dropCapImage"
			+ "    __typename"
			+ "    id"
			+ "  }"
			+ "  markups {"
			+ "    ...Markups_markup"
			+ "    __typename"
			+ "  }"
			+ "  __typename"
			+ "  id"
			+ "}"
			+ ""
			+ "fragment MarkupNode_data_dropCapImage on ImageMetadata {"
			+ "  ...DropCap_image"
			+ "  __typename"
			+ "  id"
			+ "}"
			+ ""
			+ "fragment DropCap_image on ImageMetadata {"
			+ "  id"
			+ "  originalHeight"
			+ "  originalWidth"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment Markups_markup on Markup {"
			+ "  type"
			+ "  start"
			+ "  end"
			+ "  href"
			+ "  anchorType"
			+ "  userId"
			+ "  linkMetadata {"
			+ "    httpStatus"
			+ "    __typename"
			+ "  }"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment ParagraphRefsMapContext_paragraph on Paragraph {"
			+ "  id"
			+ "  name"
			+ "  text"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment PostAnnotationsMarker_paragraph on Paragraph {"
			+ "  ...PostViewNoteCard_paragraph"
			+ "  __typename"
			+ "  id"
			+ "}"
			+ ""
			+ "fragment PostViewNoteCard_paragraph on Paragraph {"
			+ "  name"
			+ "  __typename"
			+ "  id"
			+ "}"
			+ ""
			+ "fragment TextParagraph_paragraph on Paragraph {"
			+ "  type"
			+ "  hasDropCap"
			+ "  codeBlockMetadata {"
			+ "    mode"
			+ "    lang"
			+ "    __typename"
			+ "  }"
			+ "  ...Markups_paragraph"
			+ "  ...ParagraphRefsMapContext_paragraph"
			+ "  __typename"
			+ "  id"
			+ "}"
			+ ""
			+ "fragment IframeParagraph_paragraph on Paragraph {"
			+ "  type"
			+ "  iframe {"
			+ "    mediaResource {"
			+ "      id"
			+ "      iframeSrc"
			+ "      iframeHeight"
			+ "      iframeWidth"
			+ "      title"
			+ "      __typename"
			+ "    }"
			+ "    __typename"
			+ "  }"
			+ "  layout"
			+ "  ...Markups_paragraph"
			+ "  __typename"
			+ "  id"
			+ "}"
			+ ""
			+ "fragment MixtapeParagraph_paragraph on Paragraph {"
			+ "  type"
			+ "  mixtapeMetadata {"
			+ "    href"
			+ "    mediaResource {"
			+ "      mediumCatalog {"
			+ "        id"
			+ "        __typename"
			+ "      }"
			+ "      __typename"
			+ "    }"
			+ "    __typename"
			+ "  }"
			+ "  ...GenericMixtapeParagraph_paragraph"
			+ "  __typename"
			+ "  id"
			+ "}"
			+ ""
			+ "fragment GenericMixtapeParagraph_paragraph on Paragraph {"
			+ "  text"
			+ "  mixtapeMetadata {"
			+ "    href"
			+ "    thumbnailImageId"
			+ "    __typename"
			+ "  }"
			+ "  markups {"
			+ "    start"
			+ "    end"
			+ "    type"
			+ "    href"
			+ "    __typename"
			+ "  }"
			+ "  __typename"
			+ "  id"
			+ "}"
			+ ""
			+ "fragment CodeBlockParagraph_paragraph on Paragraph {"
			+ "  codeBlockMetadata {"
			+ "    lang"
			+ "    mode"
			+ "    __typename"
			+ "  }"
			+ "  __typename"
			+ "  id"
			+ "}"
			+ ""
			+ "fragment normalizedBodyModel_richText on RichText {"
			+ "  paragraphs {"
			+ "    ...normalizedBodyModel_richText_paragraphs"
			+ "    __typename"
			+ "  }"
			+ "  sections {"
			+ "    startIndex"
			+ "    ...getSectionEndIndex_section"
			+ "    __typename"
			+ "  }"
			+ "  ...getParagraphStyles_richText"
			+ "  ...getParagraphSpaces_richText"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment normalizedBodyModel_richText_paragraphs on Paragraph {"
			+ "  markups {"
			+ "    ...normalizedBodyModel_richText_paragraphs_markups"
			+ "    __typename"
			+ "  }"
			+ "  codeBlockMetadata {"
			+ "    lang"
			+ "    mode"
			+ "    __typename"
			+ "  }"
			+ "  ...getParagraphHighlights_paragraph"
			+ "  ...getParagraphPrivateNotes_paragraph"
			+ "  __typename"
			+ "  id"
			+ "}"
			+ ""
			+ "fragment normalizedBodyModel_richText_paragraphs_markups on Markup {"
			+ "  type"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment getParagraphHighlights_paragraph on Paragraph {"
			+ "  name"
			+ "  __typename"
			+ "  id"
			+ "}"
			+ ""
			+ "fragment getParagraphPrivateNotes_paragraph on Paragraph {"
			+ "  name"
			+ "  __typename"
			+ "  id"
			+ "}"
			+ ""
			+ "fragment getSectionEndIndex_section on Section {"
			+ "  startIndex"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment getParagraphStyles_richText on RichText {"
			+ "  paragraphs {"
			+ "    text"
			+ "    type"
			+ "    __typename"
			+ "  }"
			+ "  sections {"
			+ "    ...getSectionEndIndex_section"
			+ "    __typename"
			+ "  }"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment getParagraphSpaces_richText on RichText {"
			+ "  paragraphs {"
			+ "    layout"
			+ "    metadata {"
			+ "      originalHeight"
			+ "      originalWidth"
			+ "      id"
			+ "      __typename"
			+ "    }"
			+ "    type"
			+ "    ...paragraphExtendsImageGrid_paragraph"
			+ "    __typename"
			+ "  }"
			+ "  ...getSeriesParagraphTopSpacings_richText"
			+ "  ...getPostParagraphTopSpacings_richText"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment paragraphExtendsImageGrid_paragraph on Paragraph {"
			+ "  layout"
			+ "  type"
			+ "  __typename"
			+ "  id"
			+ "}"
			+ ""
			+ "fragment getSeriesParagraphTopSpacings_richText on RichText {"
			+ "  paragraphs {"
			+ "    id"
			+ "    __typename"
			+ "  }"
			+ "  sections {"
			+ "    ...getSectionEndIndex_section"
			+ "    __typename"
			+ "  }"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment getPostParagraphTopSpacings_richText on RichText {"
			+ "  paragraphs {"
			+ "    type"
			+ "    layout"
			+ "    text"
			+ "    codeBlockMetadata {"
			+ "      lang"
			+ "      mode"
			+ "      __typename"
			+ "    }"
			+ "    __typename"
			+ "  }"
			+ "  sections {"
			+ "    ...getSectionEndIndex_section"
			+ "    __typename"
			+ "  }"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment HighlighSegmentContext_paragraph on Paragraph {"
			+ "  ...ParagraphRefsMapContext_paragraph"
			+ "  __typename"
			+ "  id"
			+ "}"
			+ ""
			+ "fragment NormalizeHighlights_paragraph on Paragraph {"
			+ "  name"
			+ "  text"
			+ "  __typename"
			+ "  id"
			+ "}"
			+ ""
			+ "fragment PostBody_creator on User {"
			+ "  ...PostNotesMarkers_creator"
			+ "  __typename"
			+ "  id"
			+ "}"
			+ ""
			+ "fragment PostNotesMarkers_creator on User {"
			+ "  id"
			+ "  name"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment ActiveSelectionContext_post on Post {"
			+ "  id"
			+ "  ...SelectionMenu_post"
			+ "  ...PostNewNoteCard_post"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment SelectionMenu_post on Post {"
			+ "  id"
			+ "  isPublished"
			+ "  isLocked"
			+ "  latestPublishedVersion"
			+ "  visibility"
			+ "  creator {"
			+ "    id"
			+ "    allowNotes"
			+ "    __typename"
			+ "  }"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment PostNewNoteCard_post on Post {"
			+ "  id"
			+ "  latestPublishedVersion"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment WithResponsesSidebar_post on Post {"
			+ "  id"
			+ "  ...ThreadedResponsesSidebar_post"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment ThreadedResponsesSidebar_post on Post {"
			+ "  id"
			+ "  ...ThreadedResponsesSidebarContent_post"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment ThreadedResponsesSidebarContent_post on Post {"
			+ "  id"
			+ "  postResponses {"
			+ "    count"
			+ "    __typename"
			+ "  }"
			+ "  collection {"
			+ "    id"
			+ "    viewerEdge {"
			+ "      id"
			+ "      isEditor"
			+ "      __typename"
			+ "    }"
			+ "    __typename"
			+ "  }"
			+ "  creator {"
			+ "    id"
			+ "    __typename"
			+ "  }"
			+ "  ...ThreadedReplies_post"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment ThreadedReplies_post on Post {"
			+ "  __typename"
			+ "  id"
			+ "  ...ThreadedReply_post"
			+ "}"
			+ ""
			+ "fragment ThreadedReply_post on Post {"
			+ "  __typename"
			+ "  id"
			+ "  ...ReadOrEditSimpleResponse_post"
			+ "  ...StoryResponse_post"
			+ "}"
			+ ""
			+ "fragment ReadOrEditSimpleResponse_post on Post {"
			+ "  __typename"
			+ "  id"
			+ "  ...SimpleResponse_post"
			+ "}"
			+ ""
			+ "fragment SimpleResponse_post on Post {"
			+ "  id"
			+ "  ...ResponseHeader_post"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment ResponseHeader_post on Post {"
			+ "  __typename"
			+ "  id"
			+ "  createdAt"
			+ "  firstPublishedAt"
			+ "  latestPublishedAt"
			+ "  creator {"
			+ "    id"
			+ "    name"
			+ "    ...UserAvatar_user"
			+ "    ...useIsVerifiedBookAuthor_user"
			+ "    ...UserMentionTooltip_user"
			+ "    __typename"
			+ "  }"
			+ "  ...ResponsePopoverMenu_post"
			+ "}"
			+ ""
			+ "fragment UserAvatar_user on User {"
			+ "  __typename"
			+ "  id"
			+ "  imageId"
			+ "  mediumMemberAt"
			+ "  membership {"
			+ "    tier"
			+ "    __typename"
			+ "    id"
			+ "  }"
			+ "  name"
			+ "  username"
			+ "  ...userUrl_user"
			+ "}"
			+ ""
			+ "fragment UserMentionTooltip_user on User {"
			+ "  id"
			+ "  name"
			+ "  username"
			+ "  bio"
			+ "  imageId"
			+ "  mediumMemberAt"
			+ "  membership {"
			+ "    tier"
			+ "    __typename"
			+ "    id"
			+ "  }"
			+ "  ...UserAvatar_user"
			+ "  ...UserFollowButton_user"
			+ "  ...useIsVerifiedBookAuthor_user"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment ResponsePopoverMenu_post on Post {"
			+ "  id"
			+ "  ...ReportUserMenuItem_post"
			+ "  ...HideResponseMenuItem_post"
			+ "  ...BlockUserMenuItem_post"
			+ "  ...UndoClapsMenuItem_post"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment ReportUserMenuItem_post on Post {"
			+ "  __typename"
			+ "  id"
			+ "  creator {"
			+ "    id"
			+ "    __typename"
			+ "  }"
			+ "  ...SusiClickable_post"
			+ "}"
			+ ""
			+ "fragment HideResponseMenuItem_post on Post {"
			+ "  __typename"
			+ "  id"
			+ "  collection {"
			+ "    id"
			+ "    viewerEdge {"
			+ "      id"
			+ "      isEditor"
			+ "      __typename"
			+ "    }"
			+ "    __typename"
			+ "  }"
			+ "  creator {"
			+ "    id"
			+ "    __typename"
			+ "  }"
			+ "}"
			+ ""
			+ "fragment BlockUserMenuItem_post on Post {"
			+ "  __typename"
			+ "  id"
			+ "  creator {"
			+ "    id"
			+ "    __typename"
			+ "  }"
			+ "}"
			+ ""
			+ "fragment UndoClapsMenuItem_post on Post {"
			+ "  id"
			+ "  clapCount"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment StoryResponse_post on Post {"
			+ "  id"
			+ "  ...ResponseHeader_post"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment PostCanonicalizer_post on Post {"
			+ "  mediumUrl"
			+ "  __typename"
			+ "  id"
			+ "}"
			+ ""
			+ "fragment PostFooterActionsBar_post on Post {"
			+ "  id"
			+ "  visibility"
			+ "  allowResponses"
			+ "  postResponses {"
			+ "    count"
			+ "    __typename"
			+ "  }"
			+ "  isLimitedState"
			+ "  creator {"
			+ "    id"
			+ "    __typename"
			+ "  }"
			+ "  collection {"
			+ "    id"
			+ "    __typename"
			+ "  }"
			+ "  ...MultiVote_post"
			+ "  ...PostSharePopover_post"
			+ "  ...OverflowMenuButtonWithNegativeSignal_post"
			+ "  ...PostPageBookmarkButton_post"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment MultiVote_post on Post {"
			+ "  id"
			+ "  creator {"
			+ "    id"
			+ "    ...SusiClickable_user"
			+ "    __typename"
			+ "  }"
			+ "  isPublished"
			+ "  ...SusiClickable_post"
			+ "  collection {"
			+ "    id"
			+ "    slug"
			+ "    __typename"
			+ "  }"
			+ "  isLimitedState"
			+ "  ...MultiVoteCount_post"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment MultiVoteCount_post on Post {"
			+ "  id"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment PostSharePopover_post on Post {"
			+ "  id"
			+ "  mediumUrl"
			+ "  title"
			+ "  isPublished"
			+ "  isLocked"
			+ "  ...usePostUrl_post"
			+ "  ...FriendLink_post"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment usePostUrl_post on Post {"
			+ "  id"
			+ "  creator {"
			+ "    ...userUrl_user"
			+ "    __typename"
			+ "    id"
			+ "  }"
			+ "  collection {"
			+ "    id"
			+ "    domain"
			+ "    slug"
			+ "    __typename"
			+ "  }"
			+ "  isSeries"
			+ "  mediumUrl"
			+ "  sequence {"
			+ "    slug"
			+ "    __typename"
			+ "  }"
			+ "  uniqueSlug"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment FriendLink_post on Post {"
			+ "  id"
			+ "  ...SusiClickable_post"
			+ "  ...useCopyFriendLink_post"
			+ "  ...UpsellClickable_post"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment useCopyFriendLink_post on Post {"
			+ "  ...usePostUrl_post"
			+ "  __typename"
			+ "  id"
			+ "}"
			+ ""
			+ "fragment UpsellClickable_post on Post {"
			+ "  id"
			+ "  collection {"
			+ "    id"
			+ "    __typename"
			+ "  }"
			+ "  sequence {"
			+ "    sequenceId"
			+ "    __typename"
			+ "  }"
			+ "  creator {"
			+ "    id"
			+ "    __typename"
			+ "  }"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment OverflowMenuButtonWithNegativeSignal_post on Post {"
			+ "  id"
			+ "  visibility"
			+ "  ...OverflowMenuWithNegativeSignal_post"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment OverflowMenuWithNegativeSignal_post on Post {"
			+ "  id"
			+ "  creator {"
			+ "    id"
			+ "    __typename"
			+ "  }"
			+ "  collection {"
			+ "    id"
			+ "    __typename"
			+ "  }"
			+ "  ...OverflowMenuItemUndoClaps_post"
			+ "  ...AddToCatalogBase_post"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment OverflowMenuItemUndoClaps_post on Post {"
			+ "  id"
			+ "  clapCount"
			+ "  ...ClapMutation_post"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment ClapMutation_post on Post {"
			+ "  __typename"
			+ "  id"
			+ "  clapCount"
			+ "  ...MultiVoteCount_post"
			+ "}"
			+ ""
			+ "fragment AddToCatalogBase_post on Post {"
			+ "  id"
			+ "  isPublished"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment PostPageBookmarkButton_post on Post {"
			+ "  ...AddToCatalogBookmarkButton_post"
			+ "  __typename"
			+ "  id"
			+ "}"
			+ ""
			+ "fragment AddToCatalogBookmarkButton_post on Post {"
			+ "  ...AddToCatalogBase_post"
			+ "  __typename"
			+ "  id"
			+ "}"
			+ ""
			+ "fragment PostReadTracker_post on Post {"
			+ "  id"
			+ "  collection {"
			+ "    slug"
			+ "    __typename"
			+ "    id"
			+ "  }"
			+ "  sequence {"
			+ "    sequenceId"
			+ "    __typename"
			+ "  }"
			+ "  content(postMeteringOptions: $postMeteringOptions) {"
			+ "    isLockedPreviewOnly"
			+ "    __typename"
			+ "  }"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment PostMetadata_post on Post {"
			+ "  id"
			+ "  socialTitle"
			+ "  socialDek"
			+ "  noIndex"
			+ "  canonicalUrl"
			+ "  mediumUrl"
			+ "  metaDescription"
			+ "  latestPublishedAt"
			+ "  visibility"
			+ "  isLimitedState"
			+ "  readingTime"
			+ "  creator {"
			+ "    name"
			+ "    twitterScreenName"
			+ "    ...userUrl_user"
			+ "    __typename"
			+ "    id"
			+ "  }"
			+ "  collection {"
			+ "    twitterUsername"
			+ "    facebookPageId"
			+ "    __typename"
			+ "    id"
			+ "  }"
			+ "  previewContent {"
			+ "    subtitle"
			+ "    __typename"
			+ "  }"
			+ "  previewImage {"
			+ "    id"
			+ "    alt"
			+ "    focusPercentX"
			+ "    focusPercentY"
			+ "    originalHeight"
			+ "    originalWidth"
			+ "    __typename"
			+ "  }"
			+ "  isShortform"
			+ "  noIndex"
			+ "  ...PostJsonLd_post"
			+ "  ...postMetaDescription_post"
			+ "  ...shortformPostMetaDescription_post"
			+ "  ...shouldIndexPost_post"
			+ "  ...shortformPostTitle_post"
			+ "  ...getTitleDetails_post"
			+ "  ...getTitleForPost_post"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment PostJsonLd_post on Post {"
			+ "  id"
			+ "  title"
			+ "  seoTitle"
			+ "  mediumUrl"
			+ "  creator {"
			+ "    name"
			+ "    username"
			+ "    ...userUrl_user"
			+ "    __typename"
			+ "    id"
			+ "  }"
			+ "  collection {"
			+ "    ...PostJsonLd_collection"
			+ "    __typename"
			+ "    id"
			+ "  }"
			+ "  previewImage {"
			+ "    id"
			+ "    focusPercentX"
			+ "    focusPercentY"
			+ "    originalWidth"
			+ "    originalHeight"
			+ "    __typename"
			+ "  }"
			+ "  isLocked"
			+ "  firstPublishedAt"
			+ "  updatedAt"
			+ "  isShortform"
			+ "  shortformType"
			+ "  ...getTitleForPost_post"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment PostJsonLd_collection on Collection {"
			+ "  id"
			+ "  name"
			+ "  domain"
			+ "  slug"
			+ "  logo {"
			+ "    ...PostJsonLd_logo"
			+ "    __typename"
			+ "    id"
			+ "  }"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment PostJsonLd_logo on ImageMetadata {"
			+ "  id"
			+ "  originalWidth"
			+ "  originalHeight"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment getTitleForPost_post on Post {"
			+ "  id"
			+ "  title"
			+ "  ...postTitle_post"
			+ "  ...getTitleDetails_post"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment postTitle_post on Post {"
			+ "  id"
			+ "  title"
			+ "  seoTitle"
			+ "  firstPublishedAt"
			+ "  ...getPostContentAsString_post"
			+ "  ...appendPostContext_post"
			+ "  collection {"
			+ "    id"
			+ "    name"
			+ "    domain"
			+ "    ...maybeAppendProductName_collection"
			+ "    __typename"
			+ "  }"
			+ "  creator {"
			+ "    name"
			+ "    __typename"
			+ "    id"
			+ "  }"
			+ "  previewContent {"
			+ "    subtitle"
			+ "    __typename"
			+ "  }"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment getPostContentAsString_post on Post {"
			+ "  content(postMeteringOptions: $postMeteringOptions) {"
			+ "    bodyModel {"
			+ "      paragraphs {"
			+ "        text"
			+ "        type"
			+ "        mixtapeMetadata {"
			+ "          href"
			+ "          __typename"
			+ "        }"
			+ "        __typename"
			+ "      }"
			+ "      __typename"
			+ "    }"
			+ "    __typename"
			+ "  }"
			+ "  __typename"
			+ "  id"
			+ "}"
			+ ""
			+ "fragment appendPostContext_post on Post {"
			+ "  id"
			+ "  sequence {"
			+ "    title"
			+ "    __typename"
			+ "  }"
			+ "  collection {"
			+ "    name"
			+ "    __typename"
			+ "    id"
			+ "  }"
			+ "  creator {"
			+ "    name"
			+ "    __typename"
			+ "    id"
			+ "  }"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment maybeAppendProductName_collection on Collection {"
			+ "  id"
			+ "  domain"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment getTitleDetails_post on Post {"
			+ "  id"
			+ "  content(postMeteringOptions: $postMeteringOptions) {"
			+ "    bodyModel {"
			+ "      ...GetTitleIndexMap_bodyModel"
			+ "      __typename"
			+ "    }"
			+ "    __typename"
			+ "  }"
			+ "  ...getPostContentAsString_post"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment GetTitleIndexMap_bodyModel on RichText {"
			+ "  paragraphs {"
			+ "    type"
			+ "    text"
			+ "    __typename"
			+ "  }"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment postMetaDescription_post on Post {"
			+ "  id"
			+ "  title"
			+ "  seoDescription"
			+ "  metaDescription"
			+ "  creator {"
			+ "    id"
			+ "    name"
			+ "    __typename"
			+ "  }"
			+ "  collection {"
			+ "    id"
			+ "    name"
			+ "    __typename"
			+ "  }"
			+ "  previewContent {"
			+ "    subtitle"
			+ "    __typename"
			+ "  }"
			+ "  ...getPostContentAsString_post"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment shortformPostMetaDescription_post on Post {"
			+ "  id"
			+ "  metaDescription"
			+ "  seoDescription"
			+ "  shortformType"
			+ "  title"
			+ "  ...getPostContentAsString_post"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment shouldIndexPost_post on Post {"
			+ "  id"
			+ "  firstPublishedAt"
			+ "  isShortform"
			+ "  shortformType"
			+ "  visibility"
			+ "  ...getPostContentAsString_post"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment shortformPostTitle_post on Post {"
			+ "  id"
			+ "  title"
			+ "  seoTitle"
			+ "  shortformType"
			+ "  ...getPostContentAsString_post"
			+ "  ...appendPostContext_post"
			+ "  collection {"
			+ "    ...maybeAppendProductName_collection"
			+ "    __typename"
			+ "    id"
			+ "  }"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment SuspendedBannerLoader_post on Post {"
			+ "  id"
			+ "  isSuspended"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment PostFooterInfo_post on Post {"
			+ "  id"
			+ "  license"
			+ "  visibility"
			+ "  ...PostFooterTags_post"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment PostFooterTags_post on Post {"
			+ "  id"
			+ "  tags {"
			+ "    __typename"
			+ "    id"
			+ "    displayTitle"
			+ "    normalizedTagSlug"
			+ "  }"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment PostBodyInserts_post on Post {"
			+ "  collection {"
			+ "    ...OverlappingAvatars_collection"
			+ "    __typename"
			+ "    id"
			+ "  }"
			+ "  creator {"
			+ "    ...OverlappingAvatars_user"
			+ "    ...PostByline_user"
			+ "    __typename"
			+ "    id"
			+ "  }"
			+ "  firstPublishedAt"
			+ "  isLocked"
			+ "  isShortform"
			+ "  readingTime"
			+ "  content(postMeteringOptions: $postMeteringOptions) {"
			+ "    isLockedPreviewOnly"
			+ "    bodyModel {"
			+ "      paragraphs {"
			+ "        ...PostBodyInserts_paragraph"
			+ "        __typename"
			+ "      }"
			+ "      sections {"
			+ "        startIndex"
			+ "        __typename"
			+ "      }"
			+ "      __typename"
			+ "    }"
			+ "    __typename"
			+ "  }"
			+ "  ...PostByline_post"
			+ "  ...useShouldShowPostPageMeter_post"
			+ "  ...PostPageMeter_post"
			+ "  __typename"
			+ "  id"
			+ "}"
			+ ""
			+ "fragment OverlappingAvatars_collection on Collection {"
			+ "  id"
			+ "  name"
			+ "  avatar {"
			+ "    id"
			+ "    __typename"
			+ "  }"
			+ "  domain"
			+ "  slug"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment OverlappingAvatars_user on User {"
			+ "  __typename"
			+ "  id"
			+ "  imageId"
			+ "  name"
			+ "  username"
			+ "  ...userUrl_user"
			+ "}"
			+ ""
			+ "fragment PostByline_user on User {"
			+ "  __typename"
			+ "  id"
			+ "  name"
			+ "  ...useIsVerifiedBookAuthor_user"
			+ "  ...userUrl_user"
			+ "  ...UserMentionTooltip_user"
			+ "  ...UserFollowButton_user"
			+ "}"
			+ ""
			+ "fragment PostBodyInserts_paragraph on Paragraph {"
			+ "  name"
			+ "  text"
			+ "  type"
			+ "  __typename"
			+ "  id"
			+ "}"
			+ ""
			+ "fragment PostByline_post on Post {"
			+ "  id"
			+ "  postResponses {"
			+ "    count"
			+ "    __typename"
			+ "  }"
			+ "  allowResponses"
			+ "  collection {"
			+ "    ...CollectionLinkWithPopover_collection"
			+ "    __typename"
			+ "    id"
			+ "  }"
			+ "  ...DraftStatus_post"
			+ "  ...shouldShowPublishedInStatus_post"
			+ "  ...PostSharePopover_post"
			+ "  ...OverflowMenuButtonWithNegativeSignal_post"
			+ "  ...MultiVote_post"
			+ "  ...PostPageBookmarkButton_post"
			+ "  ...MaybeTextToSpeech_post"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment DraftStatus_post on Post {"
			+ "  id"
			+ "  pendingCollection {"
			+ "    id"
			+ "    creator {"
			+ "      id"
			+ "      __typename"
			+ "    }"
			+ "    ...BoldCollectionName_collection"
			+ "    __typename"
			+ "  }"
			+ "  statusForCollection"
			+ "  creator {"
			+ "    id"
			+ "    __typename"
			+ "  }"
			+ "  isPublished"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment BoldCollectionName_collection on Collection {"
			+ "  id"
			+ "  name"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment shouldShowPublishedInStatus_post on Post {"
			+ "  statusForCollection"
			+ "  isPublished"
			+ "  __typename"
			+ "  id"
			+ "}"
			+ ""
			+ "fragment MaybeTextToSpeech_post on Post {"
			+ "  id"
			+ "  detectedLanguage"
			+ "  wordCount"
			+ "  isPublished"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment useShouldShowPostPageMeter_post on Post {"
			+ "  id"
			+ "  creator {"
			+ "    id"
			+ "    __typename"
			+ "  }"
			+ "  isLocked"
			+ "  lockedSource"
			+ "  content(postMeteringOptions: $postMeteringOptions) {"
			+ "    isLockedPreviewOnly"
			+ "    validatedShareKey"
			+ "    __typename"
			+ "  }"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment PostPageMeter_post on Post {"
			+ "  id"
			+ "  content(postMeteringOptions: $postMeteringOptions) {"
			+ "    isLockedPreviewOnly"
			+ "    __typename"
			+ "  }"
			+ "  ...FriendLinkMeter_post"
			+ "  ...MeterClickable_post"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment FriendLinkMeter_post on Post {"
			+ "  id"
			+ "  content(postMeteringOptions: $postMeteringOptions) {"
			+ "    ...FriendLinkMeter_postContent"
			+ "    __typename"
			+ "  }"
			+ "  creator {"
			+ "    ...FriendLinkSharer_user"
			+ "    __typename"
			+ "    id"
			+ "  }"
			+ "  ...MeterClickable_post"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment FriendLinkMeter_postContent on PostContent {"
			+ "  validatedShareKey"
			+ "  shareKeyCreator {"
			+ "    ...FriendLinkSharer_user"
			+ "    __typename"
			+ "    id"
			+ "  }"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment FriendLinkSharer_user on User {"
			+ "  id"
			+ "  name"
			+ "  ...userUrl_user"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment MeterClickable_post on Post {"
			+ "  id"
			+ "  ...UpsellClickable_post"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment PostNoteMissingToast_post on Post {"
			+ "  id"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment usePostTracking_post on Post {"
			+ "  ...usePostClientViewedReporter_post"
			+ "  ...usePostBranchView_post"
			+ "  __typename"
			+ "  id"
			+ "}"
			+ ""
			+ "fragment usePostClientViewedReporter_post on Post {"
			+ "  id"
			+ "  isPublished"
			+ "  isLocked"
			+ "  collection {"
			+ "    id"
			+ "    slug"
			+ "    __typename"
			+ "  }"
			+ "  content(postMeteringOptions: $postMeteringOptions) {"
			+ "    validatedShareKey"
			+ "    isLockedPreviewOnly"
			+ "    __typename"
			+ "  }"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment usePostBranchView_post on Post {"
			+ "  id"
			+ "  isPublished"
			+ "  isLocked"
			+ "  collection {"
			+ "    id"
			+ "    slug"
			+ "    domain"
			+ "    __typename"
			+ "  }"
			+ "  ...buildBranchViewData_post"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment buildBranchViewData_post on Post {"
			+ "  creator {"
			+ "    name"
			+ "    id"
			+ "    __typename"
			+ "  }"
			+ "  collection {"
			+ "    name"
			+ "    id"
			+ "    __typename"
			+ "  }"
			+ "  layerCake"
			+ "  primaryTopic {"
			+ "    id"
			+ "    slug"
			+ "    name"
			+ "    __typename"
			+ "  }"
			+ "  content(postMeteringOptions: $postMeteringOptions) {"
			+ "    isLockedPreviewOnly"
			+ "    __typename"
			+ "  }"
			+ "  __typename"
			+ "  id"
			+ "}"
			+ ""
			+ "fragment InResponseToEntityPreview_post on Post {"
			+ "  id"
			+ "  inResponseToEntityType"
			+ "  __typename"
			+ "}"
			+ ""
			+ "fragment PostPublishedDialog_prerequisite_post on Post {"
			+ "  id"
			+ "  creator {"
			+ "    id"
			+ "    __typename"
			+ "  }"
			+ "  collection {"
			+ "    id"
			+ "    __typename"
			+ "  }"
			+ "  __typename"
			+ "}";

	public String getOperationName() {
		return operationName;
	}

	public void setOperationName(String operationName) {
		this.operationName = operationName;
	}

	public VariablesVo getVariables() {
		return variables;
	}

	public void setVariables(VariablesVo variables) {
		this.variables = variables;
	}

	public String getQuery() {
		return query;
	}

	public void setQuery(String query) {
		this.query = query;
	}

	public GraphqlRequestVo(VariablesVo variables) {
		super();
		this.variables = variables;
	}
	
	public GraphqlRequestVo() {
		
	}
	
	
}
